/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.PedToolControl;
import dao.DaoLerListaArquivos;
import entity.ElementosTela;
import entity.PED;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging. Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Felipe
 */
public class PedToolView extends javax.swing.JFrame {
    
    
    PedToolControl ptc = new PedToolControl();
    private int[] cadCod; //vetor para armazenar o CadCod.
    
    /**
     * Creates new form PedigreeToolView
     */
    public PedToolView() {
        initComponents();
        enablePanel(false,false,false);
        
        ptc.testeLoginMySql(lblBanco);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioBtn = new javax.swing.ButtonGroup();
        modoSelecaoBtnG = new javax.swing.ButtonGroup();
        tipoDeBancoBtnG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rBtnTodosInd = new javax.swing.JRadioButton();
        rBtnEspecifico = new javax.swing.JRadioButton();
        painelCorrigirPedigree = new javax.swing.JPanel();
        lblCorrigePed = new javax.swing.JLabel();
        lblNomeArquivo = new javax.swing.JLabel();
        tfPed = new javax.swing.JTextField();
        rBtnTexto = new javax.swing.JRadioButton();
        rBtnArquivo = new javax.swing.JRadioButton();
        btnFileChooser = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        panelTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        rBtnBae = new javax.swing.JRadioButton();
        rBtnBioinfo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rodape = new javax.swing.JPanel();
        lblBanco = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuSalvar = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tipo de Operação:");

        radioBtn.add(rBtnTodosInd);
        rBtnTodosInd.setText("Carregar todos os Indivíduos");
        rBtnTodosInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnTodosIndActionPerformed(evt);
            }
        });

        radioBtn.add(rBtnEspecifico);
        rBtnEspecifico.setText("Carregar indivíduos específicos");
        rBtnEspecifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnEspecificoActionPerformed(evt);
            }
        });

        lblCorrigePed.setText("Indivíduos a serem corrigidos:");

        tfPed.setToolTipText("");
        tfPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPedActionPerformed(evt);
            }
        });

        modoSelecaoBtnG.add(rBtnTexto);
        rBtnTexto.setText("Texto");
        rBtnTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnTextoActionPerformed(evt);
            }
        });

        modoSelecaoBtnG.add(rBtnArquivo);
        rBtnArquivo.setText("Arquivo");
        rBtnArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnArquivoActionPerformed(evt);
            }
        });

        btnFileChooser.setText("Carregar Arquivo");
        btnFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCorrigirPedigreeLayout = new javax.swing.GroupLayout(painelCorrigirPedigree);
        painelCorrigirPedigree.setLayout(painelCorrigirPedigreeLayout);
        painelCorrigirPedigreeLayout.setHorizontalGroup(
            painelCorrigirPedigreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCorrigirPedigreeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCorrigirPedigreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCorrigirPedigreeLayout.createSequentialGroup()
                        .addComponent(lblCorrigePed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rBtnTexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rBtnArquivo))
                    .addGroup(painelCorrigirPedigreeLayout.createSequentialGroup()
                        .addComponent(tfPed, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFileChooser)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCorrigirPedigreeLayout.createSequentialGroup()
                .addComponent(lblNomeArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelCorrigirPedigreeLayout.setVerticalGroup(
            painelCorrigirPedigreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCorrigirPedigreeLayout.createSequentialGroup()
                .addGroup(painelCorrigirPedigreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorrigePed)
                    .addComponent(rBtnTexto)
                    .addComponent(rBtnArquivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCorrigirPedigreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFileChooser))
                .addGap(47, 47, 47)
                .addComponent(lblNomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.setMaximumSize(new java.awt.Dimension(129, 29));
        btnPesquisar.setMinimumSize(new java.awt.Dimension(129, 29));
        btnPesquisar.setPreferredSize(new java.awt.Dimension(129, 29));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Indivíduo", "Num Família", "Sexo", "Num Pai", "Num Mãe", "Inserir Ficticios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabela.setEnabled(false);
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout panelTabelaLayout = new javax.swing.GroupLayout(panelTabela);
        panelTabela.setLayout(panelTabelaLayout);
        panelTabelaLayout.setHorizontalGroup(
            panelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelTabelaLayout.setVerticalGroup(
            panelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.setPreferredSize(new java.awt.Dimension(129, 29));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar Pesquisa");
        btnLimpar.setPreferredSize(new java.awt.Dimension(129, 29));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.setPreferredSize(new java.awt.Dimension(129, 29));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        tipoDeBancoBtnG.add(rBtnBae);
        rBtnBae.setText("Baependi");
        rBtnBae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnBaeActionPerformed(evt);
            }
        });

        tipoDeBancoBtnG.add(rBtnBioinfo);
        rBtnBioinfo.setText("BioInfo");
        rBtnBioinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnBioinfoActionPerformed(evt);
            }
        });

        jLabel2.setText("Banco de Dados:");

        rodape.setBackground(new java.awt.Color(194, 188, 182));

        lblBanco.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblBanco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBanco.setText("Banco de dados");

        javax.swing.GroupLayout rodapeLayout = new javax.swing.GroupLayout(rodape);
        rodape.setLayout(rodapeLayout);
        rodapeLayout.setHorizontalGroup(
            rodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rodapeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        rodapeLayout.setVerticalGroup(
            rodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rodapeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBanco))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(518, 518, 518)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(23, 23, 23)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rBtnBae)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rBtnBioinfo))
                                    .addComponent(rBtnEspecifico)
                                    .addComponent(rBtnTodosInd)))
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(painelCorrigirPedigree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(rodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(rBtnTodosInd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rBtnEspecifico))
                    .addComponent(painelCorrigirPedigree, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnBae)
                    .addComponent(rBtnBioinfo)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(rodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu3.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Utilizar Ferramenta R");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        menuSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSalvar.setText("Salvar");
        menuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalvarActionPerformed(evt);
            }
        });
        jMenu3.add(menuSalvar);

        menuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu3.add(menuSair);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    /**Metodo que identifica o tipo de seleção e chama o metodo de controle correto.
     *     
     */
    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if (rBtnTodosInd.isSelected())
            limpar();
        try {
            adicionaItensTabela(ptc.btnPesquisar(setTela()));
        } catch (Exception ex) {
            Logger.getLogger(PedToolView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed
    
    
        /**
     * Metodo que recebe a lista e a adiciona na tabela.
     * 
     * @param lPed
     * @param tabela 
     */
    private void adicionaItensTabela(List<PED> lPed){
        DefaultTableModel tab = (DefaultTableModel) tabela.getModel();
        cadCod = new int[lPed.size()];
        
        for (int i = 0; i<lPed.size();i++) {
            cadCod[i] = lPed.get(i).getCad_cod();
            String[] linha = new String[5];
            linha[0] = lPed.get(i).getNumPart();
            linha[1] = lPed.get(i).getNumFami();
            linha[2] = lPed.get(i).getSexo();
            linha[3] = lPed.get(i).getNumPai();
            linha[4] = lPed.get(i).getNumMae();
            tab.addRow(linha);
            tab.setValueAt(false, i, 5); //coloca o valor "false para a tabela.
        }
        tabela.setEnabled(true);
    }
    
    
    /**
     * Metodo booleano para mostrar o JOptionPane.
     * @param msg
     * @return 
     */
    public static boolean jOptionPaneConfirmar(String[] msg){
        return 0 == JOptionPane.showConfirmDialog(null, msg[0],msg[1],0,
                JOptionPane.WARNING_MESSAGE);
    }
    
    public void jOptionPaneErro(String[] msg) {
        JOptionPane.showMessageDialog(null, msg[0],msg[1],JOptionPane.ERROR_MESSAGE);
    }
    
    private void rBtnArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnArquivoActionPerformed
        enablePanel(true,false,true);
    }//GEN-LAST:event_rBtnArquivoActionPerformed
    
    
    private void rBtnTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnTextoActionPerformed
        enablePanel(true,true,false);
    }//GEN-LAST:event_rBtnTextoActionPerformed

    
    private void rBtnEspecificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnEspecificoActionPerformed
        enablePanel(true,false,false);
    }//GEN-LAST:event_rBtnEspecificoActionPerformed

    
    private void rBtnTodosIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnTodosIndActionPerformed
        enablePanel(false,false,false);
    }//GEN-LAST:event_rBtnTodosIndActionPerformed


    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
       limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        if(0 == JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente sair?",
                "Sair",0,JOptionPane.PLAIN_MESSAGE))
            System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    
    private void tfPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPedActionPerformed

    
    /**
     * Botão que pede confirmação do usuário e então grava os dados no Banco.
     * @param evt 
     */
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(0 == JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente salvar?",
                "Salvar",0,JOptionPane.WARNING_MESSAGE)){
            try {
                ptc.salvarBanco(addToList(tabela));
                limpar();
                    adicionaItensTabela(ptc.btnPesquisar(setTela()));
            } catch (SQLException ex) {
                System.out.println(ex);
            } catch (Exception ex) {
                Logger.getLogger(PedToolView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    
    /**
     * Botão de menu que pede confirmação do usuário e então grava os dados no Banco.
     * @param evt 
     */
    private void menuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalvarActionPerformed
        if(0 == JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente salvar?",
                "Salvar",0,JOptionPane.WARNING_MESSAGE)){
            try {
                ptc.salvarBanco(addToList(tabela));
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_menuSalvarActionPerformed

    
    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        if(0 == JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente sair?",
                "Sair",0,JOptionPane.PLAIN_MESSAGE))
            System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    
    private void rBtnBaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnBaeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnBaeActionPerformed

    
    private void rBtnBioinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnBioinfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnBioinfoActionPerformed

    private void btnFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileChooserActionPerformed
        try {
            // TODO add your handling code here:
            String mostra = "Pesquisar indivíduos do arquivo: ";
            btnFileChooser.setText(fileChooserActionListener());
            tfPed.setEnabled(true);
        } catch (Exception ex) {
            System.out.println("erro: " + ex);
        }
    }//GEN-LAST:event_btnFileChooserActionPerformed
    
    public String fileChooserActionListener() throws Exception {
        FileNameExtensionFilter filtro = new FileNameExtensionFilter ("Arquivos TXT (.txt)","txt");
        
        JFileChooser chooser = new JFileChooser();
        
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.addChoosableFileFilter(filtro);
        
        String nomeArquivo = "";
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            DaoLerListaArquivos daoLer = new DaoLerListaArquivos();
            String caminhoArquivo = chooser.getSelectedFile().getAbsolutePath();
            nomeArquivo = chooser.getSelectedFile().getName();
            tfPed.setText(daoLer.ler(caminhoArquivo)); 
            //System.out.println(nomeArquivo);
        } else {
            System.out.println("File access cancelled by user.");
        }
        return nomeArquivo;
    }
    
    /**
     * 
     * @return 
     */
    private ElementosTela setTela(){
        ElementosTela tela = new ElementosTela();
        tela.setBtnPesquisar(btnPesquisar);
        tela.setBtnFileChooser(btnFileChooser);
        tela.setBtnSalvar(btnSalvar);
        tela.setBtnLimpar(btnLimpar);
        tela.setBtnSair(btnSair);
        tela.setTfPed(tfPed.getText());
        tela.setLblBanco(lblBanco);
        tela.setTabela(tabela);
        
        tela.setRadioTodosInd(rBtnTodosInd.isSelected());
        tela.setRadioEspecifico(rBtnEspecifico.isSelected());
        tela.setRadioBae(rBtnBae.isSelected());
        tela.setRadioBioinfo(rBtnBioinfo.isSelected());
        tela.setRadioTexto(rBtnTexto.isSelected());
        tela.setRadioArquivo(rBtnArquivo.isSelected());
        
        return tela;
    }
    
    /**
     * 
     * @param tela 
     */
    private void getTela(ElementosTela tela){
        btnFileChooser = tela.getBtnFileChooser();
        btnPesquisar = tela.getBtnPesquisar();
        btnSalvar = tela.getBtnSalvar();
        btnLimpar = tela.getBtnLimpar();
        btnSair = tela.getBtnSair();
        

        
        tfPed.setText(tela.getTfPed());
        lblBanco = tela.getLblBanco();
        tabela = tela.getTabela();
    }
    
    /**
     * metodo para facilitar a habilitação do painel. 
     * recebe os parametros como booleanos, e aplica-os na função setEnabled().
     * @param radioB
     * @param indTf
     * @param fileChooserBtn
     */
    private void enablePanel(boolean radioB, boolean indTf, boolean fileChooserBtn) {
        rBtnTexto.setEnabled(radioB);
        rBtnArquivo.setEnabled(radioB);
        tfPed.setEnabled(indTf);
        btnFileChooser.setEnabled(fileChooserBtn);
        lblCorrigePed.setEnabled(radioB);
        lblNomeArquivo.setText("");
    }
    
    /**
     * Metodo que adiciona os itens da tabela a uma lista
     * @param tabela
     * @return lPed
     */
    public List<PED> addToList(JTable tabela){
        List<PED> lPed = new ArrayList();
        
        for (int i=0; i < tabela.getRowCount(); i++){
            PED ped = new PED();
            ped.setCad_cod(cadCod[i]);
            ped.setNumPart(tabela.getValueAt(i, 0).toString());
            ped.setNumFami(tabela.getValueAt(i, 1).toString());
            ped.setSexo(tabela.getValueAt(i, 2).toString());
            ped.setNumPai(tabela.getValueAt(i, 3).toString());
            ped.setNumMae(tabela.getValueAt(i, 4).toString());
            ped.setFict(Boolean.parseBoolean(tabela.getValueAt(i, 5).toString()));
            
            lPed.add(ped);
        }
        
        return lPed;
    }
    
    /**
     * Metodo que limpa a tela 
     */
    public void limpar() {
        DefaultTableModel tab = (DefaultTableModel) tabela.getModel();
        
        tfPed.setText("");
        tab.setRowCount(0);
    }
 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFileChooser;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblCorrigePed;
    private javax.swing.JLabel lblNomeArquivo;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuSalvar;
    private javax.swing.ButtonGroup modoSelecaoBtnG;
    private javax.swing.JPanel painelCorrigirPedigree;
    private javax.swing.JPanel panelTabela;
    private javax.swing.JRadioButton rBtnArquivo;
    private javax.swing.JRadioButton rBtnBae;
    private javax.swing.JRadioButton rBtnBioinfo;
    private javax.swing.JRadioButton rBtnEspecifico;
    private javax.swing.JRadioButton rBtnTexto;
    private javax.swing.JRadioButton rBtnTodosInd;
    private javax.swing.ButtonGroup radioBtn;
    private javax.swing.JPanel rodape;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tfPed;
    private javax.swing.ButtonGroup tipoDeBancoBtnG;
    // End of variables declaration//GEN-END:variables


}
